// @generated by protobuf-ts 2.9.3
// @generated from protobuf file "greet.proto" (package "greet", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Greeter } from "./greet";
import type { ServerEventsMessage } from "./greet";
import type { ServerEventsRequest } from "./greet";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { HelloReply } from "./greet";
import type { HelloRequest } from "./greet";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * The greeting service definition.
 *
 * @generated from protobuf service greet.Greeter
 */
export interface IGreeterClient {
    /**
     * Sends a greeting
     *
     * @generated from protobuf rpc: SayHello(greet.HelloRequest) returns (greet.HelloReply);
     */
    sayHello(input: HelloRequest, options?: RpcOptions): UnaryCall<HelloRequest, HelloReply>;
    /**
     * @generated from protobuf rpc: ServerEvents(greet.ServerEventsRequest) returns (stream greet.ServerEventsMessage);
     */
    serverEvents(input: ServerEventsRequest, options?: RpcOptions): ServerStreamingCall<ServerEventsRequest, ServerEventsMessage>;
}
/**
 * The greeting service definition.
 *
 * @generated from protobuf service greet.Greeter
 */
export class GreeterClient implements IGreeterClient, ServiceInfo {
    typeName = Greeter.typeName;
    methods = Greeter.methods;
    options = Greeter.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Sends a greeting
     *
     * @generated from protobuf rpc: SayHello(greet.HelloRequest) returns (greet.HelloReply);
     */
    sayHello(input: HelloRequest, options?: RpcOptions): UnaryCall<HelloRequest, HelloReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HelloRequest, HelloReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ServerEvents(greet.ServerEventsRequest) returns (stream greet.ServerEventsMessage);
     */
    serverEvents(input: ServerEventsRequest, options?: RpcOptions): ServerStreamingCall<ServerEventsRequest, ServerEventsMessage> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ServerEventsRequest, ServerEventsMessage>("serverStreaming", this._transport, method, opt, input);
    }
}
